## Different Retriever Techniques

In [1]:
from pathlib import Path
import getpass #getpass securely reads sensitive input, such as passwords or API keys, without displaying them on the screen.
import os #provides functions for interacting with the operating system, such as reading environment variables and managing files.
import shutil #shutil provides high-level file operations such as copying, moving, and deleting files and directories.

import numpy as np
import pandas as pd

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_chroma import Chroma

C:\Users\anilp\AppData\Local\Temp\ipykernel_13052\1183619124.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader
c:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
huggingfacehub_api_token = os.getenv("huggingfacehub_api_token")

In [3]:
from langchain_huggingface import HuggingFaceEndpointEmbeddings

embeddings = HuggingFaceEndpointEmbeddings(
    model="BAAI/bge-small-en-v1.5",
    task="feature-extraction",
)

In [4]:
DATA_DIR = Path(
    r"C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals"
    r"\Class-36-29-July-2026_Retriever\data"
)

preferred_pdf = DATA_DIR / "llama2-research-paper.pdf"

if preferred_pdf.exists():
    PDF_PATH = preferred_pdf
else:
    # Automatically find the PDF if its filename is slightly different
    available_pdfs = sorted(DATA_DIR.glob("*.pdf"))

    if len(available_pdfs) == 1:
        PDF_PATH = available_pdfs[0]
    elif len(available_pdfs) == 0:
        raise FileNotFoundError(
            f"No PDF file was found inside:\n{DATA_DIR}"
        )
    else:
        raise RuntimeError(
            "Multiple PDF files were found. Please set PDF_PATH manually.\n"
            + "\n".join(str(path) for path in available_pdfs)
        )

print("PDF found:")
print(PDF_PATH)

PDF found:
C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf

In [5]:
loader=PyPDFLoader(str(PDF_PATH))

pages=loader.load()
print(f"Total Pages: {len(pages)}")

Total Pages: 77

In [6]:
print("First-page metadata:")
print(pages[0].metadata)

print("\nFirst 1,000 characters:")
print(pages[0].page_content[:1000])

First-page metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1'}

First 1,000 characters:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov

## MetaData (Customization)

In [7]:
def identify_section(paper_page: int) -> str:
    """
    Identify the major section of the Llama 2 paper
    using its printed PDF page number.
    """

    if 1 <= paper_page <= 2:
        return "front_matter"

    if 3 <= paper_page <= 4:
        return "introduction"

    if 5 <= paper_page <= 7:
        return "pretraining"

    if 8 <= paper_page <= 19:
        return "fine_tuning"

    if 20 <= paper_page <= 31:
        return "safety"

    if 32 <= paper_page <= 35:
        return "discussion"

    if paper_page == 36:
        return "conclusion"

    if 37 <= paper_page <= 45:
        return "references"

    if 46 <= paper_page <= 77:
        return "appendix"

    return "unknown"

In [8]:
for page_document in pages:
    # PyPDFLoader page index is normally zero-based
    page_index = int(page_document.metadata.get("page", 0))
    paper_page = page_index + 1

    page_document.metadata.update(
        {
            "paper": "Llama 2",
            "organization": "Meta",
            "year": 2023,
            "document_type": "research_paper",
            "paper_page": paper_page,
            "section": identify_section(paper_page),
            "access_level": "public",
        }
    )

In [9]:
for page_document in pages[:5]:
    print(page_document.metadata)

{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 1, 'page_label': '2', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 2, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 2, 'page_label': '3', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 3, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 3, 'page_label': '4', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 4, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 4, 'page_label': '5', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 5, 'section': 'pretraining', 'access_level': 'public'}

## Chunking (RecursiveCharacterText Splitter)

In [10]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    add_start_index=True,
)

chunks = text_splitter.split_documents(pages)

print(f"Total pages: {len(pages)}")
print(f"Total chunks: {len(chunks)}")

Total pages: 77
Total chunks: 343

In [11]:
## Capture the chunk number and paper page in the chunk metadata
#chunk_number is just the loop index that enumerate() produces enumerate(chunks) yields (0, chunks[0]), (1, chunks[1]), (2, chunks[2]), and so on
for chunk_number, chunk in enumerate(chunks):
    paper_page = chunk.metadata.get("paper_page", "unknown")

    chunk.metadata["chunk_id"] = (
        f"llama2-page-{paper_page}-chunk-{chunk_number}"
    )

In [12]:
print("Chunk content:")
print(chunks[0].page_content[:1100])

print("\nChunk metadata:")
print(chunks[0].metadata)

Chunk content:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic

Chunk metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': 'C:\\Mine\\AI\\Full Stack Gen AI  BootCamp (KrishNaik)\\Practicals\\Class-36-29-July-2026_Retriever\\data\\llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public', 'start_index': 0, 'chunk_id': 'llama2-page-1-chunk-0'}

## Embeddings

In [13]:
test_vector=embeddings.embed_query("What is Llama 2?")

print(f"Embedding dimenesions:{len(test_vector)}")
print(f"Embedding vector (first 10 values): {test_vector[:10]}")

Embedding dimenesions:384
Embedding vector (first 10 values): [-0.08428332209587097, -0.024261441081762314, -0.015151201747357845, 0.03341759741306305, 0.04084879532456398, -0.0009922870667651296, -0.010198874399065971, 0.008071157149970531, -0.01886812411248684, -0.02917918935418129]

In [14]:
persistDirectoryPath=Path(
r"C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals"
r"\Class-36-29-July-2026_Retriever\PersistDirectory")

PERSIST_DIRECTORY = persistDirectoryPath / "chroma_llama2_retriever"

# Set this to False when you want to reuse the existing index.
REBUILD_INDEX = True

if REBUILD_INDEX and PERSIST_DIRECTORY.exists():
    shutil.rmtree(
        PERSIST_DIRECTORY,
        ignore_errors=True
    )

In [15]:
vectorstore=Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name="llama2_retriever",
    persist_directory=str(PERSIST_DIRECTORY),
    collection_configuration={"hnsw":{"space": "cosine"}})

print("Vector Store created Successfully")
print(f"Stored Chunks: {len(chunks)}")
print(f"Vector Store Path: {PERSIST_DIRECTORY}")

Vector Store created Successfully
Stored Chunks: 343
Vector Store Path: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\PersistDirectory\chroma_llama2_retriever

In [16]:
# Load the existing Chroma collection
vector_store = Chroma(
    collection_name="llama2_retriever",
    embedding_function=embeddings,
    persist_directory=str(PERSIST_DIRECTORY),
)

print("Existing vector store loaded successfully.")
print(f"Persist directory: {PERSIST_DIRECTORY}")

Existing vector store loaded successfully.
Persist directory: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\PersistDirectory\chroma_llama2_retriever

In [17]:
def display_documents(
    documents,
    max_characters: int = 700
) -> None:
    """
    Display retrieved LangChain Document objects clearly.
    """

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(documents, start=1):
        metadata = document.metadata

        print("=" * 90)
        print(f"RANK: {rank}")
        print(f"PAPER PAGE: {metadata.get('paper_page')}")
        print(f"SECTION: {metadata.get('section')}")
        print(f"CHUNK ID: {metadata.get('chunk_id')}")
        print(f"SOURCE: {metadata.get('source')}")
        print("-" * 90)
        print(document.page_content[:max_characters])
        print()

In [18]:
similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    }
)

In [19]:
query = "What model sizes of Llama 2 were released?"
similarity_documents = similarity_retriever.invoke(query)
display_documents(similarity_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 77
SECTION: appendix
CHUNK ID: llama2-page-77-chunk-338
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
A.7 Model Card
Table 52 presents a model card (Mitchell et al., 2018; Anil et al., 2023) that summarizes details of the models.
Model Details
Model DevelopersMeta AI
Variations Llama 2comes in a range of parameter sizes—7B, 13B, and 70B—as well as
pretrained and fine-tuned variations.
Input Models input text only.
Output Models generate text only.
Model ArchitectureLlama 2isanauto-regressivelanguagemodelthatusesanoptimizedtransformer
architecture. The tuned versions use supervised fine-tuning (SFT) and reinforce-
ment learning with human feedback (RLHF) to align to human preferences for
helpfulness and safety.
Model Dates Llama 2was trained between January 2023 and July 2023.
Status This is

==========================================================================================
RANK: 2
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-27
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and ≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B outperform Falcon 7B and 40B models on all categories of benchmarks.
Additionally,Llama 2 70B model o

==========================================================================================
RANK: 3
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-28
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
in Table 4,Llama 2 70B is close to GPT-3.5 (OpenAI, 2023) on MMLU and GSM8K, but there is a significant
gap on coding benchmarks.Llama 2 70B results are on par or better than PaLM (540B) (Chowdhery et al.,
2022) on almost all benchmarks. There is still a large gap in performance betweenLlama 2 70B and GPT-4
and PaLM-2-L.
We also analysed the potential data contamination and share the details in Section A.6.
Benchmark (shots) GPT-3.5 GPT-4 PaLM PaLM-2-L Llama 2
MMLU (5-shot) 70.0 86.4 69.3 78.3 68.9
TriviaQA (1-shot) – – 81.4 86.1 85.0
Natural Questions (1-shot) – – 29.3 37.5 33.0
GSM8K (8-shot) 57.1 92.0 56.5 80.7 56.8
HumanEval (0-shot) 48.1 67.0 26.2 – 29.9
BIG-Bench Hard (3-shot) – – 52.3

==========================================================================================
RANK: 4
PAPER PAGE: 50
SECTION: appendix
CHUNK ID: llama2-page-50-chunk-227
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
SQUAD (EM) QUAC (f1)
Model Size 0-shot 1-shot 4-shot 5-shot 0-shot 1-shot
MPT 7B 59.5 62.8 62.6 62.7 38.0 37.7
MPT 30B 74.7 74.2 72.4 74.2 40.4 41.1
Falcon 7B 16.4 16.0 16.9 17.5 24.0 18.8
Falcon 40B 72.9 73.1 71.7 71.0 41.2 43.3
Llama 1
7B 60.0 62.3 63.3 62.8 38.9 32.0
13B 68.9 68.4 66.4 66.7 39.9 36.5
33B 75.5 77.0 76.3 75.6 44.1 40.3
65B 79.4 80.0 78.3 77.9 41.0 39.8
Llama 2
7B 67.2 72.3 72.6 72.5 39.4 39.7
13B 72.9 72.1 70.6 71.3 42.7 44.8
34B 77.4 78.8 77.5 77.5 42.9 44.4
70B 80.7 82.6 81.9 81.9 42.4 49.3
Table 23:Comparison to open-source models on reading comprehension (SQUAD and QUAC).
Model Size Avg AQuA-RAT LogiQA LSAT-AR LSAT-LR LSAT-RC SAT-en SAT-en (w/o Psg.) SAT-math
MPT 7B 23.

# MMR Search Type

***MMR (Maximal Marginal Relevance) retrieval — used in vector stores (LangChain, etc.) when you want results that are both relevant AND diverse, not just the top-k most similar chunks.***

**Flow**
1. Fetch 20 similar chunks (fetch_k)
2. From those 20, pick the final 4 (k) by balancing similarity to the query with dissimilarity to already-picked chunks, weighted by lambda_mult

***Note***: For RAG, 0.5 is a common default because you want the LLM to see complementary context, not the same sentence three times.

In [20]:
mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

In [21]:
query = "How was Llama 2-Chat trained and aligned?"

mmr_documents = mmr_retriever.invoke(query)

display_documents(mmr_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-29
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost Attention (GAtt), which we find helps control dialogue flow over multiple turns
(Section 3.3). See Se

==========================================================================================
RANK: 2
PAPER PAGE: 3
SECTION: introduction
CHUNK ID: llama2-page-3-chunk-9
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as conducting red-teaming and employing iterative evaluations. Additionally,
this paper contributes a th

==========================================================================================
RANK: 3
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 4
PAPER PAGE: 56
SECTION: appendix
CHUNK ID: llama2-page-56-chunk-247
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 2-Chat, ChatGPT,
PaLM-chat, Falcon
You are a helpful, respectful and honest assistant. Always answer as helpfully
as possible, while being safe. Your answers should not include any harmful,
unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that
your responses are socially unbiased and positive in nature.
If a question does not make any sense, or is not factually coherent, explain why
instead of answering something not correct. If you don’t know the answer to a
question, please don’t share false information.
MPT
<|im_start|> system
A conversation between a user and an LLM-based AI assistant. The assistant
gives helpful and honest answers.<|im_end|>
Vicuna
A

## Compare between Cosine Similarity And MMR

In [22]:
query = "How was Llama 2-Chat trained and aligned?"

similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}
)

mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

similarity_results = similarity_retriever.invoke(query)
mmr_results = mmr_retriever.invoke(query)

In [23]:
print("Similarity Search results:")
for document in similarity_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

print("\nMMR results:")
for document in mmr_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

Similarity Search results:
8 fine_tuning llama2-page-8-chunk-29
3 introduction llama2-page-3-chunk-9
5 pretraining llama2-page-5-chunk-14
1 front_matter llama2-page-1-chunk-1

MMR results:
8 fine_tuning llama2-page-8-chunk-29
3 introduction llama2-page-3-chunk-9
11 fine_tuning llama2-page-11-chunk-45
56 appendix llama2-page-56-chunk-247

**Above Comparision Explanation**

***What actually happened***

First two picks are identical in both — the most relevant chunks (page 8 fine_tuning, page 3 introduction) show up in both lists. MMR always picks the most relevant chunk first, so overlap at the top is expected.

Picks 3 and 4 diverge — this is MMR earning its keep:

- Similarity search grabbed page 5 (pretraining) and page 1 (front_matter) — likely because those chunks had high cosine similarity to the query, but they may cover overlapping ground with the top picks or with each other.

- MMR looked at what was already picked (chunks from pages 8 and 3) and asked: "what else is relevant BUT covers different ground?" It found:
    - Page 11 chunk 45 — another fine_tuning chunk, but from a different page (so likely different subtopic within fine-tuning — maybe a different technique or dataset)
    - Page 56 chunk 247 — jumps all the way to the appendix, probably pulling in supplementary details/tables the main sections didn't cover

## Now we have used score_threshold
- score_threshold: Picks chunks those are matched with provided threshold.

In [24]:
threshold_retriever = vector_store.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={
        "k": 10,
        "score_threshold": 0.64,
    }
)

In [25]:
query = "What safety techniques were used for Llama 2-Chat?"

threshold_documents = threshold_retriever.invoke(query)

display_documents(threshold_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 4
SECTION: introduction
CHUNK ID: llama2-page-4-chunk-13
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), approach to model safety (Section 4), key observations and insights (Section 5), relevant related
wor

==========================================================================================
RANK: 2
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-36
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
tworesponsestoagivenpromptaresampledfromtwodifferentmodelvariants,andvaryingthetemperature
hyper-parameter. Inadditiontogivingparticipantsaforcedchoice,wealsoaskannotatorstolabelthedegree
to which they prefer their chosen response over the alternative: either their choice issignificantly better, better,
slightly better, ornegligibly better/ unsure.
For our collection of preference annotations, we focus on helpfulness and safety. Helpfulness refers to how
well Llama 2-Chat responses fulfill users’ requests and provide requested information; safety refers to
whether Llama 2-Chat’s responses are unsafe, e.g.,“giving detailed instructions on making a bomb”could
be considered helpful but is unsaf

==========================================================================================
RANK: 3
PAPER PAGE: 2
SECTION: front_matter
CHUNK ID: llama2-page-2-chunk-4
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
4 Safety 20
4.1 Safety in Pretraining . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
4.2 Safety Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23
4.3 Red Teaming . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28
4.4 Safety Evaluation of Llama 2-Chat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29
5 Discussion 32
5.1 Learnings and Observations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 32
5.2 Limitations and Ethical Considerations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34
5.3 Res

==========================================================================================
RANK: 4
PAPER PAGE: 58
SECTION: appendix
CHUNK ID: llama2-page-58-chunk-253
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in either case.
A.4 Additional Details for Safety
A.4.1 Tension between Safety and Helpfulness in Reward Modeling
WebrieflydiscussedthetensionbetweensafetyandhelpfulnessinSection3.2.2andhowitleadstooptimizin

==========================================================================================
RANK: 5
PAPER PAGE: 3
SECTION: introduction
CHUNK ID: llama2-page-3-chunk-9
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as conducting red-teaming and employing iterative evaluations. Additionally,
this paper contributes a th

==========================================================================================
RANK: 6
PAPER PAGE: 30
SECTION: safety
CHUNK ID: llama2-page-30-chunk-131
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
(a) Overall violation percentage.
 (b)Overall safety and helpfulness mean rating.
Figure 17: Overall safety measures.Left: Llama 2-Chat has low violation percentage overall across model
sizes. Right: Llama 2-Chat has high safety and helpfulness mean rating overall across model sizes. It is
important to note that these results are subject to limitations of the prompt set, subjectivity of the review
guidelines, and subjectivity of individual raters.
• 1 - Severe safety violations
We consider a rating of 1 or 2 as violation and use violation percentage as our main evaluation metric, with
the mean rating as a supplement. Each example is annotated by three annotators and we take the majority
vote

==========================================================================================
RANK: 7
PAPER PAGE: 70
SECTION: appendix
CHUNK ID: llama2-page-70-chunk-311
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 2-Chat
7B 57.04 60.59 96.45
13B 62.18 65.73 96.45
34B 67.2 70.01 97.06
70B 64.14 67.07 97.06
Table 44: Evaluation results on TruthfulQA across different model generations.
Limitations of Benchmarks. It is important to note that these evaluations using automatic metrics are by
no means fully comprehensive, due to the complex nature of toxicity and bias in LLMs, but the benchmarks
we selected are representative of our understanding thatLlama 2-Chat improves on critical aspects of LLM
safety. Benchmark evaluation is important for assessing AI models, including chat-oriented LLMs, because
benchmarks provide a standardized and measurable way to compare different models and track progress in

==========================================================================================
RANK: 8
PAPER PAGE: 34
SECTION: discussion
CHUNK ID: llama2-page-34-chunk-146
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
questions such as:How can we effectively teach models to utilize tools?orDoes the process necessitate a substantial
dataset? Our experiments indicate that tool usage can spontaneously emerge from alignment in a zero-shot
manner. Although we never explicitly annotate tool-use usage, Figure 23 exhibits an instance where the
model demonstrated the capability to utilize a sequence of tools in a zero-shot context.
In addition, our study extended to evaluating theLlama 2-Chat with access to a calculator. The results from
this particular experiment are documented in Table 15. LLM tool use, while exciting, can also cause some
safety concerns. We encourage more community research and red teaming in t

==========================================================================================
RANK: 9
PAPER PAGE: 19
SECTION: fine_tuning
CHUNK ID: llama2-page-19-chunk-79
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generation comparison. High IRR scores (closer to 1.0) are typically seen as
better from a data quality persp

==========================================================================================
RANK: 10
PAPER PAGE: 31
SECTION: safety
CHUNK ID: llama2-page-31-chunk-136
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Llama 2-Chat shows the best performance in terms of toxicity and truthfulness. After fine-tuning,Llama
2-Chattends to have an increase in positive sentiment overall for many of the demographic groups in BOLD.
In Appendix A.4.8, we present a detailed score breakdown of model generation sentiment across different
subgroups for the bias benchmark, along with more in-depth analyses and results of truthfulness and bias.
TruthfulQA ↑ ToxiGen ↓
ChatGPT - 78.46 0.20
Falcon-instruct 7B 28.03 7.89
MPT-instruct 7B 29.99 16.33
Llama 2-Chat
7B 57.04 0.00
13B 62.18 0.00
34B 67.20 0.02
70B 64.14 0.01
Table 14: Evaluation of fine-tuned LLMs on different safety datasets.For TruthfulQA, we present the
percent

## Retrieve Chunks with their relevance score

In [26]:
query = "What safety techniques were used for Llama 2-Chat?"

scored_results = vector_store.similarity_search_with_relevance_scores(
    query=query,
    k=5,
)

for rank, (document, relevance_score) in enumerate(
    scored_results,
    start=1
):
    print("=" * 90)
    print(f"Rank: {rank}")
    print(f"Relevance score: {relevance_score:.4f}")
    print(f"Paper page: {document.metadata.get('paper_page')}")
    print(f"Section: {document.metadata.get('section')}")
    print(document.page_content[:500])

==========================================================================================
Rank: 1
Relevance score: 0.8044
Paper page: 4
Section: introduction
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of
==========================================================================================
Rank: 2
Relevance score: 0.8044
Paper page: 10
Section: fine_tuning
tworesponsestoagivenpromptaresampledfromtwodifferentmodelvariants,andvaryingthetemperature
hyper-parameter. Inadditiontogivingparticipantsaforcedchoice,wealsoaskannotatorstolabelthedegree
to which they prefer their chosen response over the alternative: either their choice issignificantly better, better,
slightly better, ornegligibly better/ unsure.
For our collection of preference annotations, we focus on helpfulness and safety. Helpfulness refers to how
well Llama 2-Chat responses fulfill users
==========================================================================================
Rank: 3
Relevance score: 0.8000
Paper page: 2
Section: front_matter
4 Safety 20
4.1 Safety in Pretraining . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
4.2 Safety Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23
4.3 Red Teaming . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28
4.4 Safety Evaluation of Llama 2-Chat . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29
5 Discussion 32
5.1 Learnings and Observa
==========================================================================================
Rank: 4
Relevance score: 0.7978
Paper page: 58
Section: appendix
while Llama 2-Chat 70B outperforms ChatGPT on factual questions. While analyzing the results for factual
questions, we noticed that examples where both models get the answer correct but annotators preferred
Llama 2-Chat response due to the style of the response. These results on factual questions do not indicate
the hallucination rate of either model. In 31, we also share the win rate by number of turns and total word
count for prompts and generation. We do not see any trends in win rate in eith
==========================================================================================
Rank: 5
Relevance score: 0.7933
Paper page: 3
Section: introduction
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to

In [27]:
metric_query = "How was reinforcement learning with human feedback used?"

candidate_documents = vector_store.similarity_search(
    metric_query,
    k=6,
)

candidate_texts = [
    document.page_content
    for document in candidate_documents
]

print(f"Candidate chunks selected: {len(candidate_texts)}")

Candidate chunks selected: 6

In [28]:
query_vector = np.asarray(
    embeddings.embed_query(metric_query),
    dtype=np.float64,
)

document_vectors = np.asarray(
    embeddings.embed_documents(candidate_texts),
    dtype=np.float64,
)

print("Query-vector shape:", query_vector.shape)
print("Document-vectors shape:", document_vectors.shape)

Query-vector shape: (384,)
Document-vectors shape: (6, 384)

In [29]:
def cosine_similarity(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    denominator = (
        np.linalg.norm(vector_a)
        * np.linalg.norm(vector_b)
    )

    if denominator == 0:
        return 0.0

    return float(
        np.dot(vector_a, vector_b) / denominator
    )


def euclidean_distance(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.linalg.norm(vector_a - vector_b)
    )


def dot_product(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.dot(vector_a, vector_b)
    )

In [30]:
metric_rows = []

for document, document_vector in zip(
    candidate_documents,
    document_vectors
):
    metric_rows.append(
        {
            "paper_page": document.metadata.get("paper_page"),
            "section": document.metadata.get("section"),
            "chunk_id": document.metadata.get("chunk_id"),
            "cosine_similarity": cosine_similarity(
                query_vector,
                document_vector
            ),
            "euclidean_distance": euclidean_distance(
                query_vector,
                document_vector
            ),
            "dot_product": dot_product(
                query_vector,
                document_vector
            ),
            "preview": document.page_content[:100].replace(
                "\n",
                " "
            ),
        }
    )

metric_table = pd.DataFrame(metric_rows)

metric_table

,paper_page,section,chunk_id,cosine_similarity,euclidean_distance,dot_product,preview
0,9,fine_tuning,llama2-page-9-chunk-34,0.804664,0.625038,0.804664,"learning rate of2 × 10−5, a weight decay of 0...."
1,10,fine_tuning,llama2-page-10-chunk-35,0.776110,0.669163,0.776110,"sampled human preferences, whereby human annot..."
2,32,discussion,llama2-page-32-chunk-138,0.769533,0.678921,0.769533,"bility, seemed a somewhat shadowy field for th..."
3,2,front_matter,llama2-page-2-chunk-3,0.766612,0.683210,0.766612,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
4,15,fine_tuning,llama2-page-15-chunk-63,0.752870,0.703036,0.752870,We iteratively improve the policy by sampling ...
5,11,fine_tuning,llama2-page-11-chunk-42,0.747711,0.710337,0.747711,Each example consists of a prompt (including p...

In [31]:
metric_table.sort_values(
    by="cosine_similarity",
    ascending=False
)[
    [
        "paper_page",
        "section",
        "cosine_similarity",
        "preview",
    ]
]

,paper_page,section,cosine_similarity,preview
0,9,fine_tuning,0.804664,"learning rate of2 × 10−5, a weight decay of 0...."
1,10,fine_tuning,0.776110,"sampled human preferences, whereby human annot..."
2,32,discussion,0.769533,"bility, seemed a somewhat shadowy field for th..."
3,2,front_matter,0.766612,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
4,15,fine_tuning,0.752870,We iteratively improve the policy by sampling ...
5,11,fine_tuning,0.747711,Each example consists of a prompt (including p...

In [32]:
metric_table.sort_values(
    by="euclidean_distance",
    ascending=True
)[
    [
        "paper_page",
        "section",
        "euclidean_distance",
        "preview",
    ]
]

,paper_page,section,euclidean_distance,preview
0,9,fine_tuning,0.625038,"learning rate of2 × 10−5, a weight decay of 0...."
1,10,fine_tuning,0.669163,"sampled human preferences, whereby human annot..."
2,32,discussion,0.678921,"bility, seemed a somewhat shadowy field for th..."
3,2,front_matter,0.683210,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
4,15,fine_tuning,0.703036,We iteratively improve the policy by sampling ...
5,11,fine_tuning,0.710337,Each example consists of a prompt (including p...

In [33]:
metric_table.sort_values(
    by="dot_product",
    ascending=False
)[
    [
        "paper_page",
        "section",
        "dot_product",
        "preview",
    ]
]

,paper_page,section,dot_product,preview
0,9,fine_tuning,0.804664,"learning rate of2 × 10−5, a weight decay of 0...."
1,10,fine_tuning,0.776110,"sampled human preferences, whereby human annot..."
2,32,discussion,0.769533,"bility, seemed a somewhat shadowy field for th..."
3,2,front_matter,0.766612,Contents 1 Introduction 3 2 Pretraining 5 2.1 ...
4,15,fine_tuning,0.752870,We iteratively improve the policy by sampling ...
5,11,fine_tuning,0.747711,Each example consists of a prompt (including p...

In [34]:
normalized_query_vector = (
    query_vector / np.linalg.norm(query_vector)
)

normalized_document_vectors = (
    document_vectors
    / np.linalg.norm(
        document_vectors,
        axis=1,
        keepdims=True
    )
)

normalized_dot_scores = (
    normalized_document_vectors
    @ normalized_query_vector
)

cosine_scores = np.asarray(
    [
        cosine_similarity(
            query_vector,
            document_vector
        )
        for document_vector in document_vectors
    ]
)

print("Cosine scores:")
print(cosine_scores)

print("\nDot product after normalization:")
print(normalized_dot_scores)

print(
    "\nAre they approximately equal?",
    np.allclose(
        cosine_scores,
        normalized_dot_scores,
        atol=1e-8,
    ),
)

Cosine scores:
[0.80466355 0.77611034 0.76953343 0.76661224 0.75287015 0.74771052]

Dot product after normalization:
[0.80466355 0.77611034 0.76953343 0.76661224 0.75287015 0.74771052]

Are they approximately equal? True

## Prefiltering

In [35]:
finetuning_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "section":"fine_tuning"
        },
    }
)

In [42]:
query = "How was Llama 2-Chat aligned with human preferences?"
fine_tuning_documents = finetuning_retriever.invoke(query)
display_documents(fine_tuning_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 2
PAPER PAGE: 19
SECTION: fine_tuning
CHUNK ID: llama2-page-19-chunk-79
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generation comparison. High IRR scores (closer to 1.0) are typically seen as
better from a data quality persp

==========================================================================================
RANK: 3
PAPER PAGE: 18
SECTION: fine_tuning
CHUNK ID: llama2-page-18-chunk-77
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for judging models for natural language generation,
including dialogue models. To evaluate the quality of

==========================================================================================
RANK: 4
PAPER PAGE: 8
SECTION: fine_tuning
CHUNK ID: llama2-page-8-chunk-29
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost Attention (GAtt), which we find helps control dialogue flow over multiple turns
(Section 3.3). See Se

In [43]:
for document in fine_tuning_documents:
    assert document.metadata.get("section") == "fine_tuning"

    print("All returned documents are from the fine_tuning section.")

All returned documents are from the fine_tuning section.
All returned documents are from the fine_tuning section.
All returned documents are from the fine_tuning section.
All returned documents are from the fine_tuning section.

## Prefiltering with Multiple Conditions

In [44]:
filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "$and":[
                {
                    "section": {
                        "$eq": "fine_tuning"
                    }
                },
                 {
                    "year": {
                        "$eq": 2023
                    }
                },
                {
                    "organization": {
                        "$eq": "Meta"
                    }
                },
            ]
        },
    }
)

In [45]:
query = "How was human preference data collected?"
filtered_documents = filtered_retriever.invoke(query)
display_documents(filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-35
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
sampled human preferences, whereby human annotators select which of two model outputs they prefer.
This human feedback is subsequently used to train a reward model, which learns patterns in the preferences
of the human annotators and can then automate preference decisions.
3.2.1 Human Preference Data Collection
Next, we collect human preference data for reward modeling. We chose a binary comparison protocol over
other schemes, mainly because it enables us to maximize the diversity of collected prompts. Still, other
strategies are worth considering, which we leave for future work.
Our annotation procedure proceeds as follows. We ask annotators to first write a prompt, then choose
between two

==========================================================================================
RANK: 2
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-41
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Dataset
Num. of
Comparisons
Avg. # Turns
per Dialogue
Avg. # Tokens
per Example
Avg. # Tokens
in Prompt
Avg. # Tokens
in Response
Anthropic Helpful 122,387 3.0 251.5 17.7 88.4
Anthropic Harmless 43,966 3.0 152.5 15.7 46.4
OpenAI Summarize 176,625 1.0 371.1 336.0 35.1
OpenAI WebGPT 13,333 1.0 237.2 48.3 188.9
StackExchange 1,038,480 1.0 440.2 200.1 240.2
Stanford SHP 74,882 1.0 338.3 199.5 138.8
Synthetic GPT-J 33,139 1.0 123.3 13.0 110.3
Meta (Safety & Helpfulness) 1,418,091 3.9 798.5 31.4 234.1
Total 2,919,326 1.6 595.7 108.2 216.9
Table 6: Statistics of human preference data for reward modeling.We list both the open-source and
internally collected human preference data used for reward mode

==========================================================================================
RANK: 3
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-39
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
against multiple open-source preference datasets including Anthropic Helpful and Harmless (Bai et al.,
2022a), OpenAI Summarize (Stiennon et al., 2020), OpenAI WebGPT (Nakano et al., 2021), StackExchange
(Lambert et al., 2023), Stanford Human Preferences (Ethayarajh et al., 2022), and Synthetic GPT-J (Havrilla).
We collected a large dataset of over 1 million binary comparisons based on humans applying our specified
guidelines, which we refer to asMetareward modeling data. Note that the number of tokens in prompts and
answers differs depending on the text domain. Summarization and online forum data generally have longer
prompts, while dialogue-style prompts are usually shorter. Compared to ex

==========================================================================================
RANK: 4
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-44
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
do so, we further add a margin component in the loss:
Lranking = −log(σ(rθ(x, yc) − rθ(x, yr) − m(r))) (2)
where the marginm(r) is a discrete function of the preference rating. Naturally, we use a large margin
for pairs with distinct responses, and a smaller one for those with similar responses (shown in Table 27).
We found this margin component can improve Helpfulness reward model accuracy especially on samples
where two responses are more separable. More detailed ablation and analysis can be found in Table 28 in
Appendix A.3.3.
Data Composition. We combine our newly collected data with existing open-source preference datasets
to form a larger training dataset. Initially, open-source datase

## Prefilter

In [46]:
pre_filter = {
    "$and": [
        {
            "section": {
                "$eq": "fine_tuning"
            }
        },
        {
            "year": {
                "$eq": 2023
            }
        },
    ]
}

pre_filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": pre_filter,
    }
)

pre_filtered_documents = pre_filtered_retriever.invoke(
    "How was the reward model trained?"
)

display_documents(pre_filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-40
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we train two separate reward
models, one optimized for helpfulness (referred to asHelpfulness RM) and anoth

==========================================================================================
RANK: 2
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-42
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Each example consists of a prompt (including previous dialogue if available) and a response, which is the
input of the reward model. We report the number of comparisons, the average number of turns per dialogue,
the average number of tokens per example, per prompt and per response. More details on Meta helpfulness
and safety data per batch can be found in Appendix A.3.1.
knows. This prevents cases where, for instance, the two models would have an information mismatch, which
could result in favoring hallucinations. The model architecture and hyper-parameters are identical to those
of the pretrained language models, except that the classification head for next-token prediction is replaced
with

==========================================================================================
RANK: 3
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 4
PAPER PAGE: 12
SECTION: fine_tuning
CHUNK ID: llama2-page-12-chunk-46
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Helpfulness reward model is eventually trained on all Meta Helpfulness data, combined with an equal
parts of the remaining data uniformly sampled from Meta Safety and from the open-source datasets. The
Meta Safety reward model is trained on all Meta Safety and Anthropic Harmless data, mixed with Meta
Helpfulness and open-source helpfulness data in a 90/10 proportion. We found that the setting with 10%
helpfulness data is especially beneficial for the accuracy on samples where both the chosen and rejected
responses were deemed safe.
Training Details. We train for one epoch over the training data. In earlier experiments, we found that
training longer can lead to over-fitting. We use the same o

## PostFiltering

In [49]:
unfiltered_retriever_candidates = vector_store.similarity_search(
    query="How was the reward model trained?", k=15)

In [51]:
post_filtered_documents = [
document
for document in unfiltered_retriever_candidates
if document.metadata.get("section") == "fine_tuning"
and document.metadata.get("year") == 2023
]

display_documents(post_filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-40
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we train two separate reward
models, one optimized for helpfulness (referred to asHelpfulness RM) and anoth

==========================================================================================
RANK: 2
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-42
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Each example consists of a prompt (including previous dialogue if available) and a response, which is the
input of the reward model. We report the number of comparisons, the average number of turns per dialogue,
the average number of tokens per example, per prompt and per response. More details on Meta helpfulness
and safety data per batch can be found in Appendix A.3.1.
knows. This prevents cases where, for instance, the two models would have an information mismatch, which
could result in favoring hallucinations. The model architecture and hyper-parameters are identical to those
of the pretrained language models, except that the classification head for next-token prediction is replaced
with

==========================================================================================
RANK: 3
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: llama2-page-11-chunk-45
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

==========================================================================================
RANK: 4
PAPER PAGE: 12
SECTION: fine_tuning
CHUNK ID: llama2-page-12-chunk-46
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Helpfulness reward model is eventually trained on all Meta Helpfulness data, combined with an equal
parts of the remaining data uniformly sampled from Meta Safety and from the open-source datasets. The
Meta Safety reward model is trained on all Meta Safety and Anthropic Harmless data, mixed with Meta
Helpfulness and open-source helpfulness data in a 90/10 proportion. We found that the setting with 10%
helpfulness data is especially beneficial for the accuracy on samples where both the chosen and rejected
responses were deemed safe.
Training Details. We train for one epoch over the training data. In earlier experiments, we found that
training longer can lead to over-fitting. We use the same o

==========================================================================================
RANK: 5
PAPER PAGE: 14
SECTION: fine_tuning
CHUNK ID: llama2-page-14-chunk-58
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
reward_max (T=1)
reward_max (T=1.1)
reward_max (T=1.2)
reward_max (T=1.3)
reward_max (T=1.4)
reward_max (T=1.5)
Figure8: RLHFimpactofthetemperature whensamplingNoutputsandscoringthemwitharewardmodel.
Rejection Sampling. We perform rejection sampling only with our largest 70BLlama 2-Chat. All smaller
models are fine-tuned on rejection sampled data from the larger model, thus distilling the large-model
capabilities into the smaller ones. We leave further analysis of the effect of this distillation for future work.
At each iterative stage, we sampleK answers for each prompt from the most recent model. We score each
sample given the best reward model accessible at the time of the experiment, and

==========================================================================================
RANK: 6
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: llama2-page-10-chunk-35
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
sampled human preferences, whereby human annotators select which of two model outputs they prefer.
This human feedback is subsequently used to train a reward model, which learns patterns in the preferences
of the human annotators and can then automate preference decisions.
3.2.1 Human Preference Data Collection
Next, we collect human preference data for reward modeling. We chose a binary comparison protocol over
other schemes, mainly because it enables us to maximize the diversity of collected prompts. Still, other
strategies are worth considering, which we leave for future work.
Our annotation procedure proceeds as follows. We ask annotators to first write a prompt, then choose
between two

==========================================================================================
RANK: 7
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-54
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
evaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.
Therefore, everything else being equal, an improvement of the reward model can be directly translated into
an improvement forLlama 2-Chat.
3.2.3 Iterative Fine-Tuning
As we received more batches of human preference data annotation, we were able to train better reward
models and collect more prompts. We therefore trained successive versions for RLHF models, referred to
here as RLHF-V1, ..., RLHF-V5.
We explored RLHF fine-tuning with two main algorithms:
• Proximal Policy Optimization (PPO)(Schulman et al., 2017), the standard in RLHF literature.
• RejectionSamplingfine-tuning . Wesampl

==========================================================================================
RANK: 8
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: llama2-page-13-chunk-51
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
1 2 3 4 5 6 7 8 9 10 11 12 13 14
Meta Helpfulness Data Batch Stage
0.52
0.54
0.56
0.58
0.60
0.62
0.64Accuracy On All Examples
 7b
13b
70b
GPT4
OpenAssistant
1 2 3 4 5 6 7 8 9 10 11 12 13 14
Meta Helpfulness Data Batch Stage
0.50
0.55
0.60
0.65
0.70
0.75
0.80Accuracy On Examples With Label "Significantly Better"
7b
13b
70b
GPT4
OpenAssistant
Figure 6: Scaling trends for the reward model.More data and a larger-size model generally improve
accuracy, and it appears that our models have not yet saturated from learning on the training data.
The fact that helpfulness and safety performed the best on their own domain is potentially due to the tension
betweenthetwoobjectives(i.e.,beingashelpfulasposs

==========================================================================================
RANK: 9
PAPER PAGE: 15
SECTION: fine_tuning
CHUNK ID: llama2-page-15-chunk-63
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
We iteratively improve the policy by sampling promptsp from our datasetD and generationsg from the
policy π and use the PPO algorithm and loss function to achieve this objective.
The final reward function we use during optimization,
R(g | p) = ˜Rc(g | p) − βDKL (πθ(g | p) ∥ π0(g | p)) (4)
contains a penalty term for diverging from the original policyπ0. As was observed in other works (Stiennon
et al., 2020; Ouyang et al., 2022), we find this constraint is useful for training stability, and to reduce reward
hackingwherebywewouldachievehighscoresfromtherewardmodelbutlowscoresfromhumanevaluation.
We defineRc to be a piecewise combination of the safety (Rs) and helpfulness (Rh) reward models. We

==========================================================================================
RANK: 10
PAPER PAGE: 17
SECTION: fine_tuning
CHUNK ID: llama2-page-17-chunk-74
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
answers based on a 7-point Likert scale (the higher the better). We observe that our reward models overall
are well calibrated with our human preference annotations, as illustrated in Figure 29 in the appendix. This
confirms the relevance of using our reward as a point-wise metric, despite being trained with a Pairwise
Ranking Loss.
Still, as Goodhart’s Law states, when a measure becomes a target, it ceases to be a good measure. To ensure
ourmeasurewon’tdivergefromthehumanpreferences,weadditionallyusedamoregeneralreward,trained
17

==========================================================================================
RANK: 11
PAPER PAGE: 14
SECTION: fine_tuning
CHUNK ID: llama2-page-14-chunk-56
SOURCE: C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Class-36-29-July-2026_Retriever\data\llama2-research-paper.pdf
------------------------------------------------------------------------------------------
100 101
N Samples
0.54
0.56
0.58
0.60
0.62
0.64
0.66Reward Score
Max of the rewards
Median of the rewards
Figure 7: Max and median reward among N samples, N ∈ [1, . . . ,100] averaged over our training set of
prompts. The delta between max and median can be interpreted as potential gain with Rejection Sampling.
the highest reward score is considered the new gold standard. Similar to Scialom et al. (2020a), we
then fine-tune our model on the new set of ranked samples, reinforcing the reward.
The two RL algorithms mainly differ in:
• Breadth— in Rejection Sampling, the model exploresK samples for a given prompt, while only one
generation is done for PPO.
• Depth— in PPO, during training at ste

In [54]:
print("Prefilter Return Documents.",len(unfiltered_retriever_candidates))
print("Post-filtered Documents.",len(post_filtered_documents))

Prefilter Return Documents. 15
Post-filtered Documents. 11

In [55]:
import os
from typing import List

from pydantic import BaseModel, Field

from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers.ensemble import EnsembleRetriever

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

In [56]:
def display_documents(
    documents,
    title: str = "Retrieved Documents",
    max_documents: int = 10,
    max_characters: int = 600,
) -> None:
    """Display retrieved LangChain Document objects."""

    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(
        documents[:max_documents],
        start=1,
    ):
        metadata = document.metadata

        print(f"\nRANK: {rank}")
        print(f"Paper page: {metadata.get('paper_page')}")
        print(f"Section: {metadata.get('section')}")
        print(f"Chunk ID: {metadata.get('chunk_id')}")
        print("-" * 100)
        print(document.page_content[:max_characters])

In [57]:
def deduplicate_documents(documents):
    """Remove duplicate retrieved chunks while preserving their order."""

    unique_documents = []
    seen_keys = set()

    for document in documents:
        key = (
            document.metadata.get("chunk_id")
            or (
                document.metadata.get("source"),
                document.metadata.get("page"),
                document.page_content,
            )
        )

        if key not in seen_keys:
            seen_keys.add(key)
            unique_documents.append(document)

    return unique_documents

## Sparse (BM25) Retrieval
- BM25 is advance version of TF\IDF,Ranking algorithm used in information Retrieval.
- BM25 doenst required Vector Store
- It works on Keywords Search
- Very Long Documents are normalised as well.(It adjust Lengthy documents)

***BM25 Flow***
```text
Reads Query
   ||
   Finds matching Documents
   ||
   Computes Term Importance
   ||
   Adjusts docs Length
   ||
   Ranks documents


***Note: It is used in VectorLess RAG***

In [58]:
from langchain_community.retrievers import BM25Retriever

In [59]:
bm25_retriever = BM25Retriever.from_documents(chunks)

In [60]:
bm25_retriever

BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x000002C211CBC510>)

In [67]:
# Final number of results
bm25_retriever.k = 4
sparse_query = "Grouped-Query Attention GQA 70B"

In [68]:
sparse_documents = bm25_retriever.invoke(sparse_query)

In [69]:
display_documents(
    sparse_documents,
    title="Sparse Retrieval: BM25 Results",
)

====================================================================================================
Sparse Retrieval: BM25 Results
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 2
Paper page: 48
Section: appendix
Chunk ID: llama2-page-48-chunk-220
----------------------------------------------------------------------------------------------------
BoolQ PIQA SIQA Hella-Swag ARC-e ARC-c NQ TQA MMLU GSM8K Human-Eval
MHA 71.0 79.3 48.2 75.1 71.2 43.0 12.4 44.7 28.0 4.9 7.9
MQA 70.6 79.0 47.9 74.5 71.6 41.9 14.5 42.8 26.5 4.8 7.3
GQA 69.4 78.8 48.6 75.4 72.1 42.5 14.0 46.2 26.9 5.3 7.9
Table 18: Attention architecture ablations.We report 0-shot results for all tasks except MMLU(5-shot) and
GSM8K(8-shot). For GSM8K and Human-Eval we report maj@1 and pass@1 results. For NQ and TriviaQA
we report EM. For all other tasks we report accuracy.
Figure 24: Multi-query variants enable higher throughput with larger batch sizes, and show similar
latenc

RANK: 3
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 4
Paper page: 48
Section: appendix
Chunk ID: llama2-page-48-chunk-221
----------------------------------------------------------------------------------------------------
memory error at a batch size of 1024 for a context of 256 tokens and at a batch size of 128 for 2k context,
whereas MQA and GQA have successful runs in those settings.
Therefore, based on the ablation results and ease of scaling inference, for the 34B and 70BLlama 2 models
we chose to use GQA instead of MQA.
Figure 24 shows how inference speed changed for the 30B GQA and MQA ablation models compared to the
MHA baseline, in an experiment using 8 x 80 GiB A100s with tensor parallelism. In these runs we simply
duplicated the KV heads for MQA in all GPUs, so the KV cache size for MQA became equal

## Dense Retrieval
- It does Semantic Search

In [70]:
dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    },
)

In [71]:
dense_query = (
    "How did Meta improve inference scalability "
    "for the largest Llama 2 models?"
)

dense_documents = dense_retriever.invoke(dense_query)

display_documents(
    dense_documents,
    title="Dense Retrieval: Vector Search Results",
)

====================================================================================================
Dense Retrieval: Vector Search Results
====================================================================================================

RANK: 1
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 2
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

RANK: 3
Paper page: 19
Section: fine_tuning
Chunk ID: llama2-page-19-chunk-79
----------------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generatio

RANK: 4
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

In [72]:
comparison_query = (
    "How did grouped-query attention improve "
    "Llama 2 inference scalability?"
)

sparse_results = bm25_retriever.invoke(comparison_query)
dense_results = dense_retriever.invoke(comparison_query)

display_documents(
    sparse_results,
    title="BM25 Results",
    max_documents=4,
)

display_documents(
    dense_results,
    title="Dense Vector Results",
    max_documents=4,
)

====================================================================================================
BM25 Results
====================================================================================================

RANK: 1
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 2
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 3
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 4
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

====================================================================================================
Dense Vector Results
====================================================================================================

RANK: 1
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-216
----------------------------------------------------------------------------------------------------
Table 16 compares the performance of 2k and 4k context pretraining on long-context benchmarks. Both
modelsaretrainedfor150Btokens,keepingthesamearchitectureandhyperparametersasabaseline,varying
only the context length. We observe improvement on SCROLLS (Shaham et al., 2022), where the average
input length is 3.5k, and no performance degradation on SQUAD (Rajpurkar et al., 2018). Table 17 shows
that the longer context model retains strong performance on various general-purpose tasks.
Grouped-Query Attention. A standard practice for autoregressive decoding is to cache the key (K) and
value (V) p

RANK: 2
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

RANK: 3
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 4
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

In [73]:
print("SPARSE RESULTS")
for rank, document in enumerate(sparse_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

print("\nDENSE RESULTS")
for rank, document in enumerate(dense_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

SPARSE RESULTS
1 4 llama2-page-4-chunk-12
2 47 llama2-page-47-chunk-217
3 54 llama2-page-54-chunk-240
4 6 llama2-page-6-chunk-18

DENSE RESULTS
1 47 llama2-page-47-chunk-216
2 13 llama2-page-13-chunk-53
3 3 llama2-page-3-chunk-9
4 6 llama2-page-6-chunk-18

In [74]:
bm25_retriever.k = 8

dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 8
    },
)

## Hybrid Retriever
- It has both BM25 & Dense Retriever
- Weights are provided for each Retriver technique

In [75]:
from langchain_classic.retrievers.ensemble import EnsembleRetriever
hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, dense_retriever],
    weights=[0.5 #BM25 Weight
             , 0.5 #Dense Weight
             ]
)

In [76]:
hybrid_query = (
    "Llama 2 70B grouped-query attention and inference scalability"
)

In [78]:
hybrid_documents = hybrid_retriever.invoke(hybrid_query)

In [80]:
display_documents(
    hybrid_documents,
    title="Hybrid Retrieval: BM25 + Dense ",
    max_documents=6,
)

====================================================================================================
Hybrid Retrieval: BM25 + Dense
====================================================================================================

RANK: 1
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-217
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 2
Paper page: 4
Section: introduction
Chunk ID: llama2-page-4-chunk-12
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 3
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 4
Paper page: 47
Section: appendix
Chunk ID: llama2-page-47-chunk-216
----------------------------------------------------------------------------------------------------
Table 16 compares the performance of 2k and 4k context pretraining on long-context benchmarks. Both
modelsaretrainedfor150Btokens,keepingthesamearchitectureandhyperparametersasabaseline,varying
only the context length. We observe improvement on SCROLLS (Shaham et al., 2022), where the average
input length is 3.5k, and no performance degradation on SQUAD (Rajpurkar et al., 2018). Table 17 shows
that the longer context model retains strong performance on various general-purpose tasks.
Grouped-Query Attention. A standard practice for autoregressive decoding is to cache the key (K) and
value (V) p

RANK: 5
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 6
Paper page: 5
Section: pretraining
Chunk ID: llama2-page-5-chunk-16
----------------------------------------------------------------------------------------------------
We performed a variety of pretraining data investigations so that users can better understand the potential
capabilities and limitations of our models; results can be found in Section 4.1.
2.2 Training Details
We adopt most of the pretraining setting and model architecture fromLlama 1. We use the standard
transformer architecture (Vaswani et al., 2017), apply pre-normalization using RMSNorm (Zhang and
Sennrich, 2019), use the SwiGLU activation function (Shazeer, 2020), and rotary positional embeddings
(RoPE, Su et al. 2022). The primary architectural differences fromLlama 1 include increased c

In [86]:
test_query = (
    "How did Meta make Llama 2 70B efficient for large-scale inference?"
) 

sparse_results = bm25_retriever.invoke(test_query)
dense_results = dense_retriever.invoke(test_query)
hybrid_results = hybrid_retriever.invoke(test_query)

In [87]:
display_documents(
    sparse_results,
    title="1. Sparse Retrieval",
    max_documents=4,
)

display_documents(
    dense_results,
    title="2. Dense Retrieval",
    max_documents=4,
)

display_documents(
    hybrid_results,
    title="3. Hybrid Retrieval",
    max_documents=4,
)

====================================================================================================
1. Sparse Retrieval
====================================================================================================

RANK: 1
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 2
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

RANK: 3
Paper page: 51
Section: appendix
Chunk ID: llama2-page-51-chunk-229
----------------------------------------------------------------------------------------------------
Model Size GSM8k MATH
MPT 7B 6.8 3.0
30B 15.2 3.1
Falcon 7B 6.8 2.3
40B 19.6 5.5
Llama 1
7B 11.0 2.9
13B 17.8 3.9
33B 35.6 7.1
65B 50.9 10.6
Llama 2
7B 14.6 2.5
13B 28.7 3.9
34B 42.2 6.24
70B 56.8 13.5
Table 25: Comparison to other open-source models on mathematical reasoning tasks, GSM8k and MATH
(maj1@1 is reported).
Mathematical Reasoning. In Table 25, we report results forLlama 2 and other open-source datasets on the
GSM8k and MATH tasks.
A.3 Additional Details for Fine-tuning
A.3.1 Detailed Statistics of Meta Human Preference Data
Table 26 shows detailed statistics on Meta human preferenc

RANK: 4
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-241
----------------------------------------------------------------------------------------------------
adapted as an efficient technique for long context attention.
A.3.6 How Far Can Model-Based Evaluation Go?
To measure the robustness of our reward model, we collected a test set of prompts for both helpfulness and
safety, and asked annotators to judge quality of the answers based on a 7 point Likert-scale (the higher the
better) using triple reviews. As illustrated in Figure 29 (in Appendix), we observe that our reward models
overallarewellcalibratedwithhumanpreference. Notethatthisenablesustousetherewardasapoint-wise
metric, despite being trained with a Pairwise Ranking Loss.
0.0% 2.0% 4.0% 6

====================================================================================================
2. Dense Retrieval
====================================================================================================

RANK: 1
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 2
Paper page: 35
Section: discussion
Chunk ID: llama2-page-35-chunk-154
----------------------------------------------------------------------------------------------------
this progression is the rise of Llama, recognized for its focus on computational efficiency during inference
(Touvron et al., 2023). A parallel discourse has unfolded around the dynamics of open-source versus closed-
source models. Open-source releases like BLOOM (Scao et al., 2022), OPT(Zhang et al., 2022), and Falcon
(Penedo et al., 2023) have risen to challenge their closed-source counterparts like GPT-3 and Chinchilla.
§§https://ai.meta.com/llama
35

RANK: 3
Paper page: 1
Section: front_matter
Chunk ID: llama2-page-1-chunk-1
----------------------------------------------------------------------------------------------------
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov Thomas Scialom∗
GenAI, Meta
Abstract
In this work, we develop and release Llama 2, a collection of pretrained and fine-tuned
large language models (LLMs) ranging in scale from 7 billion to 70 billion parameters.
Our fine-tuned LLMs, calledLlama 2-Chat, are optimized for dialogue use cases. Our
models outperform open-source chat models on most benchmarks we tested, and based on
our human evaluations for helpfulness and

RANK: 4
Paper page: 13
Section: fine_tuning
Chunk ID: llama2-page-13-chunk-53
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

====================================================================================================
3. Hybrid Retrieval
====================================================================================================

RANK: 1
Paper page: 8
Section: fine_tuning
Chunk ID: llama2-page-8-chunk-27
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and ≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B o

RANK: 2
Paper page: 54
Section: appendix
Chunk ID: llama2-page-54-chunk-240
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 3
Paper page: 3
Section: introduction
Chunk ID: llama2-page-3-chunk-9
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 4
Paper page: 6
Section: pretraining
Chunk ID: llama2-page-6-chunk-18
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0 × 10−4
13B 2k ✗ 1.0T 3.0 × 10−4
33B 2k ✗ 1.4T 1.5 × 10−4
65B 2k ✗ 1.4T 1.5 × 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0 × 10−4
13B 4k ✗ 2.0T 3.0 × 10−4
34B 4k ✓ 2.0T 1.5 × 10−4
70B 4k ✓ 2.0T 1.5 × 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 15

## Query Rewriting